AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an EC2 instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-090abff6ae1141d7d  # Replace with your desired AMI ID
      InstanceType: t3.micro
      KeyName: NAT  # Replace with your key pair name
      SecurityGroups:
        - Ref: MySecurityGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: madhavbucket